using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

public class ChoiceHolder : MonoBehaviour
{
    public List<string> dateA;
    public List<string> dateB;
    public List<string> dateC;


    public void Start()
    {
        dateA = new List<string>
        { 
            "Player: I've never been the type of person to get dates at the drop of a hat. But when I found out Sam and Blake were getting married I knew I couldn’t show my face without a plus one. But knowing me I knew the only chance I had was getting someone to set me up on a blind date. Luckily my friend Dr. Busman has set me up with a date today. Now my only challenge is to get them to be my plus one to Sam and Blake's wedding.=next #2",
            "Robbin: I’ve been waiting for 25 minutes. But Dr. Busman has never let me down so I’ll give you another shot.= Player: Well this place is impossible to find. There is virtually no parking. I’m PLAYER_NAME by the way. #3= Player: Well the weather has been terrible. What was I supposed to do? #3= Player: Well you see my watch broke last week and I ordered a new one online but when it came it was set an hour behind. #3",
            "Robbin: Well PLAYER_NAME you should probably plan ahead better next time. Oh and you can call me DATE.= Well have you ordered yet? #4= Have you eaten yet #4= This place is kind of whack Do you wanna just get out of here? #4",
            "No. I waited for you. But I can call the waiter over.= Next #5",
            "Waiter: Good evening. I will be your waiter this evening. May I start you two off with something to drink.= I'll have a Pepper Margarita served in a Red Pepper #6= I'll have a Cherry Lane #6= I'll have the Red Beards Rum Barrel #6",
            "Waiter and for you= next #7",
            "Robbin: Just water is fine.= Come on Robbin it's the weekend order whatever you want. My treat. #8= Just water? Are you one of those “hydrate or die-drate” people? Get something else, my treat. #8= Water is so last year! Have something exciting. My treat #8",
            "Robbin: Water is fine. [Looks at PLAYER_NAME. Looks at waiter on “fine”= next #9",
            "Waiter: and do you need more time to decide what to order?= next #10",
            "Robbin: I know what I want but I think PLAYER_NAME needs more time to decide.= Yeah just give me a few minutes to look over the menu. #11= Hmmm, this is more difficult than the Cheesecake Facility! #11= Should I have the chicken or the soup? #11",
            "The waiter leaves and the player looks over the menu for a few minutes in silence. = next #12",
            "Player: [Thinks’] “Man when is that waiter coming back. I’ve known I wanted the soup of the day for the last five minutes and now I can’t think of anything to say.” = next #13",
            "Robbin: Uhmmm… hello? = Oh hi sorry still deciding.  #14 = Oh, didn’t see ya there! Haha #14 = Ummmm… hello to you! #14",
            "The waiter returns = next #15",
            "Waiter: Have you decided yet? = next #16",
            "Player: Yes I’ll have the soup of the day. = next #17",
            "Robbin: and I’ll have the fish. = next #18",
            "Waiter: Absolutely. May I take your menus? = next #19",
            "Robbin and Player hand the waiter their menus. = next #20",
            "Robbin: Did it really take you that long just to choose the soup of the day…? = Well I wasn't sure if I wanted soup or chicken. #21  = Yeah, there are so many days and so many soups, so many flavorful combinations. #21  = To be honest, I’ve always known I wanted soup, it just took me a while to realize it. #21",
            "Robbin: … oh = next #22",
            "Robbin: So… Did you grow up around here? = Yeah #23  = What? In this restaurant? Oh.. no. I’m from Kalendyr. #23  = You could say I grew up around here. #23",
            "Robbin: Oh? Where about’s? How about sharing some details? = Well I grew up on 14th and west street. My family had the same apartment for over 15 years. I went to Castell regional highschool. #24  = Kalendyr is a small town, there is not much to it. Most of us are artisans, woodworkers, etc. #24  = I’d rather not say... But do you know the Kalendyr area? #24",
            "Robbin: Oh I knew some people from there. Do you know Gregory Surf? = next #25",
            "Player: No… can’t say that I do. But I feel like that name is familiar. I never really hung out with people outside of my highschool’s woodworking club. You would have thought that people in the woodworking club would have been really close, but there was actually a lot of drama. I remember this one time... = next #26",
            "You ramble about woodworking club drama until your food arrives = next #27",
            "Waiter: and for you, the soup of the day. = Wow this soup looks amazing! #28 = This soup is the most gorgeous  thing in this room! #28 = Look at this! So sweet and beautiful. How was it made, where were all the components grown. I have so many questions about this soup. #28",
            "Robbin: The soup? = next #29",
            "Player: Yeah, haven’t you ever had soup that was just divine?= next #30",
            "Robbin: The best soup I ever had was last summer when I was in Italy… = next #31",
            "Player: OH! I’ve been to Italy before. My senior year of high school the woodworking club took a trip to Italy. We went and saw all the famous wood in Italy. You would have thought that the woodworking drama would have stayed in highschool but it followed us there. Dave just wouldn’t stop harassing Alton… = Keep talking about woodworking. #32 = Tell a story about woodworking. #32 = Talk about that one time in Italy when Alton took Dave’s wood and it just got ugly. #32",
            "You spend the rest of the evening retelling what you remember as a gripping woodworking drama tale. = next #33",
            "Waiter: Thank you so much for joining us this evening and here is your check. = next #34",
            "Player frantically searches their pockets for money = next #35",
            "Robbin: Don’t tell me… you forgot the money, right!? = next #36",
            "Player: Well... funny story, actually this reminds me of a time in Italy with the woodworking clu- = next #37",
            "Robbin: IF YOU MENTION THE WOODWORKING CLUB ONE MORE TIME! You know what… I’m out of here. = next #38",
        };

        dateB = new List<string>
        {
            "Robin: Well PLAYER_MAN you should probably plan ahead better next time. = ...what #2",
            "Robin: Well, = next #3",
            "Player: I just saw you get hit by a bus... = next #4",
            "Robin: Excuse me? =  next #5",
            "Player: You were just leaving and as you were crossing the street a bus just hit you. = next #6",
            "Robin: What are you talking about? I've been sitting here waiting for you. Can we just order? = next #7",
            "Robin: Waiter! = next #8",
            "Robin calls over the waiter. = #9",
            "Waiter: Good evening. I will be your waiter this evening. May I start you two off with something to drink? = Wait didn’t we already order? #10 = Didn’t you see Robin get hit by that bus? #11 ",
            "Response: Well I’ve been here a few times but Robin asked me to wait until you arrived. = next #12",
            "Response: Hit by a bus? I think I would remember something like that. = next #12",
            "Robin: Just water is fine for me. = next #13",
            "Player: I must have hit my head pretty hard when I fainted. Uh… I guess just a water for me too. = next #14",
            "Waiter: Very good and do you know what entres you will be having this evening = next #15",
            "Robin: I know what I want but I think PLAYER_NAME needs more time to decide. = next #16",
            "Waiter: Very well then. = next #17",
            "The waiter leaves and the player looks over the menu for a few minutes in silence. I’m not sure if I’m even hungry anymore. #18 = I was watching you leave, you started crossing the street, and then out of nowhere this bus comes and hits you.  #19 = How can you think about food right now? #20",
            "Well you need to get something I’m not gonna eat by myself. = next #21",
            "I think I would remember if something like that happened. You should check out the fish I hear it's great! = next #21",
            "Well we’re at a restaurant why wouldn’t I be. = next #21",
            "Player: So you don’t remember when I told you about my woodworking trip to Italy? = next #22",
            "Robin: Again this is the first time we’ve met. But I was in Italy last summer. They have some of the best cuisine in the world… = next #23",
            "Robin talks about their trip to Italy until the waiter returns with the drinks. = next #24",
            "Waiter: Here are your waters and have we decided on entres? = next #25",
            "Robin: I’ll have the fish. = Maybe you don’t remember because you hit your head after the bus hit you. #26 = But you look fine. I can’t even see a single scrape.  #26 = I was expecting to wake up in an ambulance or something.  26#",
            "Robin: I’m sorry about him, maybe just a second order of the fish. = next #27",
            "Waiter: Very good choice. = next #28",
            "Player: God! Why am I the only one that remembers anything! = next #29",
            "Robin: Why can’t I have ONE normal date… = next #30",
            "Player: [Thinks’] “Man, when is that waiter coming back. I’ve known I wanted the soup of the day for the last five minutes and now I can’t think of anything to say.” = next #31",
            " Are we in some sort of time loop?  = next #32",
            "Robin: Time loop? I’ve heard some bad excuses for being late but this is the worst one yet. You know what I’m out of here.  = next #33",
            "Player: No you can’t leave. If you walk out that door you’re going to die! = next #34",
            "Robin: Ever since you arrived here you’ve been acting weird, talking about this “time loop”. If you think this is going to work on me you are sorely mistaken. I have better things to do with my time then waste them on some lunatic.  = next #35",
            "Robin gets up from the table and starts to walk towards the door. Player gets up and tries to stop her before she reaches the door.  = next #36",
            "Robin: Get your hands off me! = next #37",
            "Player: Please don’t. = next #38",
            "The waiter pulls the player off of Robin. = next #39",
            "Waiter: Come on buddy just let the nice lady go. She doesn’t want to eat with you. = next #40",
            "Player: Please you have to stop her. She’s going to die. = next #41",
            "Robin steps out of the restaurant. = next #42",
            "Robin: See I’m fi- = next #43",
        };

        dateC = new List<string>
        {
            "Robin: Well PLAYER_NAME you should probably plan ahead better next time.  = next #2",
            "Player: Okay, It’s happening again.  Play it cool, PLAYER_NAME.  If she has a nice time on the date, she won’t walk away and get hit by the bus.  =  Well let's order. I’ve been excited to try this place. #3 = I’ll get the waiter. #3 = This place is kind of whack. Do you wanna just get out of here? #4",
            "Player calls over the waiter. = next #5",
            "Robin: No I think it's fine. Lets just order. Robin calls over the waiter. = next #5",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        };
    }
}